## ■ 다음주 월요일에 파이썬 시험 ncs 5문제 유형

1. 합성곱 연산
2. 이진 탐색
3. 버블 정렬

4. 탐욕 알고리즘
5. 재귀 알고리즘

60점 이하 재시험  
시간제한 있음 but 프로그램 사용 가능.  

### ■ 머신러닝과 딥러닝 때 사용할 이미지를 클래스당 1000장 다운로드 받아 32 x 32 로 일괄 사이즈 조정하고 numpy   
### array 변환해서 오라클 db 저장

__예)__

코스모스 사진과 장미꽃 분류

코뿔소와 코끼리 사진 분류  

## 4. 탐욕알고리즘

탐욕 알고리즘은 매 순간마다 최선의 선택을 하게 하는 것입니다.  
선택할 때마다 가장 좋다고 생각되는 것을 선택해 나가며  
최종적인 해답을 구하는 알고리즘 입니다.  
이 알고리즘을 설계할 때 주의할 점은 전체를 고려하는게 아니라  
문제를 부분적으로 나누어, 나누어진 문제에 대한 최적의 해답을 구하게끔 해야한다는 점 입니다.  


__예)__ : 14원의 잔돈을 줘야하는데 잔돈의 종류가 10원, 7원, 1원이 있으면 잔돈을 가장 빨리 줄 수 있는 방법?

__일반 :__ 7원 2개

__탐욕알고리즘 :__ 10원 동전 1개, 7원 동전 0개, 1원 동전 4개 (일이 더 많아짐.)

## 문제273.( 전체 문제 )  
## 아래와 같이 greey함수를 구현하시오!

print(greedy())

잔돈 총액 ? 14

결과 : 10원 동전 1개, 7원 동전 0개, 1원 동전 4개

## 문제274. (작은 문제들) 거스름돈의 종류를 입력하게 하고 거스름돈을 정렬하는 greedy 함수를 생성하시오.

print(greedy())

거스름돈의 종류를 입력하세요 ~ 7, 1, 10

[10,7,1]

In [1]:
def greedy():
    
    a, b, c = input("거스름돈의 종류를 입력하세요").split(',')
    print(a)
    print(b)
    print(c)
    
    x = [a,b,c]
    
    sal = list(map(int,x))
    
    sal.sort(reverse=True)
    return sal

print(greedy())

거스름돈의 종류를 입력하세요7,10,1
7
10
1
[10, 7, 1]


In [16]:
def greedy():
    cash_type = [int(x) for x in input('거스름돈?').split(',')]
    cash_type.sort(reverse = True)
    return cash_type

print(greedy())

거스름돈?7,1,10
[10, 7, 1]


## 문제275. 14를 10으로 나눈 나머지값과 몫을 구하시오! (divmod)

In [22]:
print(list(divmod(14,10)))

[1, 4]


## 문제276. 14를 10으로 나눈 나머지값과 몫을 따로 따로 출력하시오.

In [21]:
x = 14 // 10 #몫

y = 14%10 #나머지

print (x)
print (y)

1
4


## 문제 277. 위의 두개의 문제의 코드를 잘 조합해서 greedy()함수를 구현하시오~

print(greedy())

잔돈 액수를 입력하세요~ 29

거스름돈의 단위를 입력하세요 10,7,1

10원 2개 , 7원 2개, 1원 2개

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 12 14:04:29 2019

@author: wdp
"""

def greedy() : 

    target = int(input("거슬러 줘야하는 금액을 입력하세요 ~ : "))

    L = input("거스름돈의 종류를 입력하세요 ~ : ").split(",")



    coin = sorted([int(L[i]) for i in range(len(L))], reverse = True)



    for i in range(len(coin)) : 

        case = target//coin[i]

        target = target%coin[i]

        print("{0}원 동전 {1}개".format(coin[i], case))  # end = ' '

        

greedy()

## 문제278. 위의 코드를 수정해서 결과가 가로로 총 출력되게 하시오!

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 12 14:21:56 2019

@author: wdp
"""

L = input("잔돈의 종류를 입력하세요 ~ : ").split(",") # 문자열 요소로 리스트로 저장됨.

target = int(input('거스름돈의 금액을 입력하세요.'))

a = list(map(int,L))
a.sort(reverse = True)
print(a)


for i in range(len(a)):
    coin = target // a[i]
    target = target % a[i]
    
    print(a[i], '동전', coin, '개', end = '')

## 5. 재귀 알고리즘

### 재귀 함수란?

반복문 + 스택구조가 결합된 함수이다.

후입선출(나중에 들어간게 먼저 나오는 구조)


### - 재귀 함수의 특징? (후입선출)

재귀함수는 함수 내에서 다시 자신을 호출한 후 그 함수가 끝날때까지 함수 호출 이후의 명령문을 수행하지 않는다.

## 함수내에서 다른 함수를 호출하는 예제

In [ ]:
def hap(a,b):
    return (a+b)

def gob(a,b):
    return (a*b)
    
def hap_gob(a,b):
    k = hap(a,b)
    m = gob(a,b)
    return k+m


print(hap_gob(2,3))

## 예제1. 구구단 2단을 출력하는 함수를 생성하시오!

print(multi_talbe_2(9))

2x1 = 2  
2x2 = 2  
.....  

In [ ]:
# 재귀 함수 안쓰고

def multi_talbe_2(n):
    for i in range(1,n+1):
        print('2 *', i, '=', 2*i)

multi_talbe_2(9)

In [ ]:
# 재귀 함수 쓰고

def multi_table_2(n):
    if n == 0:
        print('end')
    else:
        multi_table_2(n-1)
        print('2x', n, '=', 2*n)

multi_table_2(9)

## ※ 재귀함수의 장점

1. 코드가 간결해진다.
2. 루프문을 사용하지 않아도 된다.

__단점:__ 가독성 & 느려질 수 있음.

## 문제279. (재귀 사용하지 말고) 함수를 만들어서 1~5 까지의 합을 출력하시오!

print(add_fun(5))

In [ ]:
def add_fun(a):
    sum1 = 0
    for i in range(1,a+1):
        sum1 += i
    
    return sum1

print(add_fun(5))

## 문제280. 위의 문제를 재귀함수를 써서 만들어보시오!

In [ ]:
def add_fun(n):
    if n == 0:
        return 0
    else:
        return n + add_fun(n-1)
    
print(add_fun(5))

## 머신러닝과 딥러닝 떄 사용할 사진을 스크롤링 하세요! (Day15 코드 참고)

__예__ :

개 vs 고양이

코스모스 vs 백합

etc...

클래스 한개당 1000장 
총 2000장

1. 웹스크롤링하고 
2. 32x32 사이즈 줄이는거까지 하기.

## ■ 스크롤링한 이미지를 csv로 저장하는 방법

1. 폐사진을 100장이 있는 폴더 이름이 무엇인지 알아낸다.

   - 현재경로 : D:\\image


2. 폐 사진을 로드하는 image_load 함수를 가져온다.

In [ ]:
import   os
import   re
import  cv2
import  numpy as np
test_image = "d:\\image"

def  image_load(path):
    file_list = os.listdir(path)
    file_name = []
    for i  in   file_list:
        a = int(  re.sub('[^0-9]','', i ) )  # 숫자 아닌것은 '' 으로 처리
        file_name.append(a) 
        file_name.sort()

    file_res =[ ]
    for  j  in   file_name:
        file_res.append( '%s\\%d.png' %(path,j) )

    image = [  ]
    for  k  in  file_res:
        img = cv2.imread(k)  # 이미지를 숫자로 변환하는 역활
        image.append(img)

    return  np.array(image)  # 숫자리스트를 numpy array 로 감싸서 리턴

print  ( image_load(test_image) )

### 3. 2차원 리스트를 1차원 리스트로 변경하시오~

In [7]:
import numpy as np

a = [[2,3,4],[4,5,6]]

a2 = np.array(a)

print(a2.ndim) # numpy array의 차원을 확인하는 방법(ndim)
print(a2)

b = a2.flatten() # 2차원 리스트를 1차원 리스트로 바꾸기 flatten

print(b)

2
[[2 3 4]
 [4 5 6]]
[2 3 4 4 5 6]


### 4. 폐사진을 1차원으로 펴서 출력하시오~

In [8]:
import   os
import   re
import  cv2
import  numpy as np
test_image = "d:\\image"

def  image_load(path):
    file_list = os.listdir(path)
    file_name = []
    for i  in   file_list:
        a = int(  re.sub('[^0-9]','', i ) )  # 숫자 아닌것은 '' 으로 처리
        file_name.append(a) 
        file_name.sort()

    file_res =[ ]
    for  j  in   file_name:
        file_res.append( '%s\\%d.png' %(path,j) )

    image = [  ]
    for  k  in  file_res:
        img = cv2.imread(k)  # 이미지를 숫자로 변환하는 역활
        image.append(img)

    return  np.array(image)  # 숫자리스트를 numpy array 로 감싸서 리턴

# 함수안에어 함수를 호출함!

def image_csv(path):
    n_2 = image_load(path)
    for i in n_2:
        i2 = i.flatten()
        return i2


print(image_csv(test_image))

[16 16 16 ... 90 90 90]


### 5. 위의 리스트를 csv파일로 저장하시오!

In [ ]:
# 최종 final 버전
# 적용하기 전에 file_res.append 부분에서 이미지 양식 잘 확인하기 (.jpg .png등등)

import   os
import   re
import  cv2
import  numpy as np
test_image = "d:\\image"

def  image_load(path):
    file_list = os.listdir(path)
    file_name = []
    for i  in   file_list:
        a = int(  re.sub('[^0-9]','', i ) )  # 숫자 아닌것은 '' 으로 처리
        file_name.append(a) 
        file_name.sort()

    file_res =[ ]
    for  j  in   file_name:
        file_res.append( '%s\\%d.png' %(path,j) )

    image = [  ]
    for  k  in  file_res:
        img = cv2.imread(k)  # 이미지를 숫자로 변환하는 역활
        image.append(img)

    return  np.array(image)  # 숫자리스트를 numpy array 로 감싸서 리턴

# 함수안에어 함수를 호출함!

def image_csv(path):
    n_2 = image_load(path)
    for i in n_2:
        i2 = i.flatten()
        np.savetxt('d:\\data\\array.csv', [i2], delimiter = ',', fmt = '%d') 
        
# fmt : 데이터 형식은 %d 정수형
# 'array.csv' 파일이름 (위치 안써주면 워킹디렉토리에 떨어짐.)
# delimiter : 데이터들을 ','(콤마)로 구분함.
        
print(image_csv(test_image))

## 문제 281.(점심시간문제) 내가 스크롤링한 이미지를 csv로 저장하시오.

In [ ]:
# 최종 final 버전
# 적용하기 전에 file_res.append 부분에서 이미지 양식 잘 확인하기 (.jpg .png등등)
import   os
import   re
import  cv2
import  numpy as np
test_image = "d:\\resizedogs"

def  image_load(path):
    file_list = os.listdir(path)
    file_name = []
    for i  in   file_list:
        a = int(  re.sub('[^0-9]','', i ) )  # 숫자 아닌것은 '' 으로 처리
        file_name.append(a) 
        file_name.sort()

    file_res =[ ]
    for  j  in   file_name:
        file_res.append( '%s\\%d.jpg' %(path,j) )

    image = [  ]
    for  k  in  file_res:
        img = cv2.imread(k)  # 이미지를 숫자로 변환하는 역활
        image.append(img)

    return  np.array(image)  # 숫자리스트를 numpy array 로 감싸서 리턴

# 함수안에어 함수를 호출함!

def image_csv(path):
    n_2 = image_load(path)
    for i in n_2:
        i2 = i.flatten()
        np.savetxt('d:\\array2.csv', [i2], delimiter = ',', fmt = '%d') 
        
# fmt : 데이터 형식은 %d 정수형
# 'array.csv' 파일이름 (위치 안써주면 워킹디렉토리에 떨어짐.)
# delimiter : 데이터들을 ','(콤마)로 구분함.
        
print(image_csv(test_image))