http://cafe.daum.net/oracleoracle/ScIc/240

## 문제79. 구구단 2단에서 ~ 9단까지 출력하시오

In [ ]:
# feed_dict 기능 숙지하기.

import tensorflow as tf

x = tf.Variable(0) # x 변수 선언하면서 0을 할당
y = tf.Variable(0) # y 변수 선언하면서 0을 할당
z = tf.multiply(x,y) # x와 y를 곱한 값이 z에 할당되게 한다.

init = tf.global_variables_initializer() #위에서 변수를 생성했으면 반드시
                                         # 변수를 초기화 해주어야한다.
sess = tf.Session() # 텐서플로우 그래프를 실행할 세션을 sess로 선언한다.
sess.run(init) # init 변수를 실행한다.

for i in range(2,10):
    for j in range(1,10):
        print(i, 'x', j, '=', sess.run(z, feed_dict = {x:i, y:j}))
        # feed_dict 명령어로 데이터를 텐서 그래프에 주입한다.
        # x변수에는 i의 값을 대입하고 y변수에는 j값을 대입한다.
        # z를 실행하기 위해서 x와 y에 값을 대입한다.
        
sess.close() # sess.close()로 마무리하는걸 잊지 말자. or with절로 시작하면 됨.

## ■ 신경망에서 bias를 만드는 코드를 텐서 플로우로 구현하는 방법

## 예제1. 변수에 숫자 0과 숫자 1을 채워넣는 배열을 생성

In [1]:
# numpy로 구현

import numpy as np

a = np.zeros((2,2))
b = np.ones((2,2))

print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
# tensorflow 로 구현하는 방법

import tensorflow as tf

a = tf.zeros((2,2))
b = tf.ones((2,2))  # 그래프 그리는 영역
init = tf.global_variables_initializer()
#------------------------------------------
                    # 그래프 실행하는 영역

sess = tf.Session()
sess.run(init)

print(sess.run(a))
print(sess.run(b))

sess.close()

## ■ 배열의 원소중에서 최대값 원소의 인덱스를 찾는 코드

1. 파이썬의 numpy를 이용하는 방법
2. tensorflow를 이용하는 방법

In [5]:
# 1. 파이썬의 numpy를 이용하는 방법

import numpy as np

a = np.array([0,0,0,1,0,0,0,0,0,0])
print(np.argmax(a, axis = 0)) # 0은 열, 1은 행

3


In [ ]:
# 2. tensorflow를 이용하는 방법

import tensorflow as tf
import numpy as np

a = np.array([0,0,0,1,0,0,0,0,0,0])
b = tf.argmax(a, axis=0)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

print(sess.run(b))
sess.close()

## ■ 다차원 배열에서 행의 토탈값을 구하는 방법

In [7]:
# numpy 로 구현
import  numpy  as  np

a = np.array([[[1, 2, 3],

               [2, 1, 4],

               [5, 2, 1],

               [6, 3, 2]],

              [[5, 1, 3],

               [1, 3, 4],

               [4, 2, 6],

               [3, 9, 3]],

              [[4, 5, 6],

               [7, 4, 3],

               [2, 1, 5],

               [4, 3, 1]]])

print (np.sum(a, axis = 0))

[[10  8 12]
 [10  8 11]
 [11  5 12]
 [13 15  6]]


In [ ]:
# 2. tensorflow로 구현
import  tensorflow  as  tf
import  numpy  as  np

a = np.array([[[1, 2, 3],

               [2, 1, 4],

               [5, 2, 1],

               [6, 3, 2]],

              [[5, 1, 3],

               [1, 3, 4],

               [4, 2, 6],

               [3, 9, 3]],

              [[4, 5, 6],

               [7, 4, 3],

               [2, 1, 5],

               [4, 3, 1]]])
    
d = tf.reduce_sum(a, reduction_indices=[0])
sess = tf.Session()
print(sess.run(d))

## ■ 텐서 플로우로 행렬 내적하는 코드

1. numpy 형식
2. tensorflow 형식

In [8]:
# 1. numpy 형식
import numpy as np

a = np.array([[2,2,2],[2,2,2]])
b = np.array([[3,3],[3,3],[3,3]])

result = np.dot(a,b)
print(result)

[[18 18]
 [18 18]]


In [ ]:
# 2. tensorflow 형식

import tensorflow as tf

x = tf.placeholder("float", [2,3]) # 2x3 행렬의 실수형 데이터를 담을 변수
y = tf.placeholder("float", [3,2]) # 3x2 행렬의 실수형 데이터를 담을 변수

result = tf.matmul(x,y) # matmul이 내적임.
init = tf.global_variables_initializer()

sess= tf.Session()
sess.run(init)
print(sess.run(result, feed_dict = {x: [[2,2,2],[2,2,2]], \
                                        y : [[3,3],[3,3],[3,3]]}))
sess.close()

## ■ 문제80. (점심시간 문제) 아래의 행렬을 tensorflow로 내적하시오.

In [ ]:
import tensorflow as tf

x = tf.placeholder("float", [3,3]) # 2x3 행렬의 실수형 데이터를 담을 변수
y = tf.placeholder("float", [3,3]) # 3x2 행렬의 실수형 데이터를 담을 변수

result = tf.matmul(x,y) # matmul이 내적임.
init = tf.global_variables_initializer()

sess= tf.Session()
sess.run(init)
print(sess.run(result, feed_dict = {x: [[6,3,2],[7,5,4], [8,9,10]], \
                                        y : [[3,4,6],[5,9,7],[6,7,4]]}))
sess.close()

## ■ 신경망에서 정확도를 출력하는 코드

" tensorflow의 cast 함수의 이해 " 

## ■ 예제 : 아래의 배열의 True를 1로 변경하고 False를 0으로 변경시키시오~

In [ ]:
import tensorflow as tf


correct_prediction = [ True, False , True  ,True  ,True  ,True  ,True,  True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True, False , True  ,True, False , True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True,

  True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True ,False , True  ,True  ,True  ,True  ,True

  ,True  ,True, False , True, False , True  ,True  ,True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True

 ,False , True  ,True  ,True]

sess = tf.Session()
a = tf.cast(correct_prediction, "float") # tf.cast : True는 1로 False는 0으로 바꾸는 함수
print(sess.run(a))

## 문제81. 위의 출력된 결과에서 전체 갯수중에 1이 몇개나 되는지 정확도가 아래와 같이 출력되게 하시오!

결과 : 0.93

In [ ]:
import tensorflow as tf


correct_prediction = [ True, False , True  ,True  ,True  ,True  ,True,  True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True, False , True  ,True, False , True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True,

  True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True ,False , True  ,True  ,True  ,True  ,True

  ,True  ,True, False , True, False , True  ,True  ,True  ,True  ,True  ,True  ,True

  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True

 ,False , True  ,True  ,True]

sess = tf.Session()
a = tf.cast(correct_prediction, "float")
b = tf.reduce_mean(a)
print(sess.run(b))

## ■ 텐서 플로우에서 mnist 데이터 가져오기

" 텐서플로우는 기본적으로 실습용으로 mnist 데이터가 내장되어 있다. "

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

batch_xs, batch_ys = mnist.train.next_batch(100)
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

print(batch_xs.shape) # (100, 784)
print(batch_ys.shape) # (100, 10)

## 문제82. mnist데이터에서 test 데이터 100개를 불러오시오~

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

batch_xs, batch_ys = mnist.test.next_batch(100) # test라 테스트 데이터
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

print(batch_xs.shape) # (100, 784)
print(batch_ys.shape) # (100, 10)

## ■ 텐서 플로우에서 배치 단위로 데이터를 불러올때 None의 의미는?

### 예제1. 아래의 숫자 2로 채워진 행렬 2x3행렬을 텐서플로우로 구성하시오

2 2 2   
2 2 2  
2 2 2   
  .
  .
  
#### ※ None으로 작성하게 되면 입력되는 행수가 몇개가 들어오던 관계 없다는 뜻이다.

In [ ]:
import tensorflow as tf
x = tf.placeholder("float", [2,3]) # 2x3 행렬을 담을 변수를 생성
sess = tf.Session()
print(sess.run(x, feed_dict = {x:[[2,2,2],[2,2,2]]}))

## 예제2. 위의 코드에서 [2,3] ---> [None,3]으로 변경해서 실행하시오

In [ ]:
import tensorflow as tf
x = tf.placeholder("float", [None,3]) # None으로 인해 행은 아무행이더라도 가능해진다.
sess = tf.Session()
print(sess.run(x, feed_dict = {x:[[2,2,2],[2,2,2]]}))

## 문제83. mnist 데이터 784(28x28) 개에 맞게 x 변수를 placeholder로 선언하고 배치로 입력될 데이터의 갯수는 몇개이든 관계없이 None을 사용한 변수를 만들고 Mnist 데이터를 x변수에 100개를 담고 출력해보시오

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
x = tf.placeholder("float", [None,784])

batch_xs, batch_ys = mnist.train.next_batch(100)

sess = tf.Session()
print(sess.run(x, feed_dict = {x:batch_xs}).shape) # (100, 784)

## ■ 텐서 플로우로 신경망을 만들때 가중치를 생성하는 코드

In [ ]:
import tensorflow as tf

W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
# -1 ~ 1 사이의 숫자로 784 x 50 행렬의 변수를 W1로 생성한다.

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(W1).shape) # (784,50)
sess.close()

## ■ Mnist 훈련데이터 100개와 785x50의 가중치와 내적한 결과의 shape를 출력하시오!

100 x784 ◎ 784 x 50 = 100 x 50

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
y = tf.matmul(x, W1)

batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y, feed_dict={x: batch_xs}))

sess.close()

## ■ 1x50 으로 bias를 생성하는데 변수를 b로 해서 생성하고 숫자 1로 다채우는방법

In [ ]:
import tensorflow as tf

b = tf.Variable(tf.ones([50]))
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

print(sess.run(b))
sess.close()

## ■ 문제84. mnist 훈련데이터 100개와 785x50의 가중치와 내적한 결과와 bias의 합을 구현하시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b = tf.Variable(tf.ones([50]))
y = tf.matmul(x, W1) +b


batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y, feed_dict = { x: batch_xs}))

sess.close()

## 문제85. 위의 내적한 결과 y를 시그모이드 함수를 통과시켜서 y_hat으로 출력되게 하시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b = tf.Variable(tf.ones([50]))
y = tf.matmul(x, W1) +b
y_hat = tf.nn.sigmoid(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_hat, feed_dict = { x: batch_xs }))

sess.close()

## 문제86. 위의 활성화 함수를 sigmoid에서 relu로 변경하시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b = tf.Variable(tf.ones([50]))
y = tf.matmul(x, W1) +b
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_hat, feed_dict = { x: batch_xs }))

sess.close()

## 문제87. 위의 1층 신경망을 통과한 y_hat과 50x10 행렬인 W2와 내적한 결과에 1x10으로 만든 b2의 합을 z로 출력되겠끔 코드를 추가하시오

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2

# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(z, feed_dict = { x: batch_xs }))

sess.close()

## 문제88. 위에 2층에서 나온 z 값을 softmax 함수를 통과시켜 나온 z_hat으로 구현하시오

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)

# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(z_hat, feed_dict = { x: batch_xs }))

sess.close()

## 문제89. 위의 출력된 확률백터에서 인덱스 번호를 출력하시오! (100개가 출력이 됨.)
## tf.argmax를 사용하고 y_predict에 담으시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_predict, feed_dict = { x: batch_xs }))

sess.close()

## 문제90. 위의 코드에 라벨(정답)을 가져오는 코드를 추가해서 정확도를 출력하시오

In [ ]:
# 아직 학습은 안함.
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(accuracy, feed_dict = { x: batch_xs, y_onehot : batch_ys }))

sess.close()

## ■ 텐서플로우 신경망 학습 시키는 코드

__" 학습을 시키기 위해서 필요한 함수 "__

1. 오차함수
    - 평균 제곱오차 : 회귀분석  
        예 : loss = tf.square(y_predict, y_label)
        
        
    - 교차 엔트로피 : 분류문제(p.115 참고)  
        예 : loss = -tf.reduce_sum(y_onehot * tf.log(y_hat), axis = 1)     ## y_onehot = t(target)


2. 경사감소법 함수
    - SGD
    - Momentum
    - Adagrade
    - Adam

## ■ 경사감소법을 텐써 플로우로 구현하는 방법

## SGD : 

 미니배치만큼 랜덤으로 데이터를 추출해서 확률적으로 경사를 감소 하여 global minima 로 찾아가는 방법 



단점 :  Local minima 에 잘 빠진다. 

#### optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)


## Adagrade:

러닝 레이트가 학습되면서 자동 조절되는 경사감소법 

#### optimizer = tf.train.AdagradOptimizer(learning_rate=0.01)



## Momentum

관성을 이용해서 local minima 에 안빠지게 하는 경사감소법 

#### optimizer = tf.train.MomentumOptimizer(learning_rate=0.01)


## Adam

Adagrade 의 장점 + Momentum 의 장점 
#### optimizer = tf.train.AdamOptimizer(learning_rate=0.01)

## 문제91. 지금까지의 텐서플로우 신경망 코드에 오차함수인 교차엔트로피 함수를 추가하고 loss를 출력하시오

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 오차 확인
loss = -tf.reduce_sum(y_onehot * tf.log(z_hat), axis = 1)
# softmax를 통과한것을 tf.log부분에 넣어야 되기 때문에 z_hat이 들어간다.

# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(loss, feed_dict = { x: batch_xs, y_onehot : batch_ys }))

sess.close()

## 문제92. 지금까지 만든 코드에 Adam 경사 감소법 코드를 추가해서 학습이 되게 하시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 오차 확인
loss = -tf.reduce_sum(y_onehot * tf.log(z_hat), axis = 1)
# softmax를 통과한것을 tf.log부분에 넣어야 되기 때문에 z_hat이 들어간다.

# 학습 시키는 코드
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)

# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(loss, feed_dict = { x: batch_xs, y_onehot : batch_ys }))

sess.run(train, feed_dict = { x: batch_xs, y_onehot : batch_ys }))
sess.close()

## 문제93. 위의 오차가 100개 나오지 말고 100개의 평균값으로 출력되게하시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 오차 확인
loss = -tf.reduce_sum(y_onehot * tf.log(z_hat), axis = 1)
result = tf.reduce_mean(loss)
# softmax를 통과한것을 tf.log부분에 넣어야 되기 때문에 z_hat이 들어간다.

# 학습 시키는 코드
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)


# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(result, feed_dict = { x: batch_xs, y_onehot : batch_ys }))

sess.run(train, feed_dict = { x: batch_xs, y_onehot : batch_ys })
sess.close()

## 문제94. 위의 결과를 오차가 아니라 정확도가 출력되게 코드를 수정하시오.

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 오차 확인
loss = -tf.reduce_sum(y_onehot * tf.log(z_hat), axis = 1)
result = tf.reduce_mean(loss)
# softmax를 통과한것을 tf.log부분에 넣어야 되기 때문에 z_hat이 들어간다.

# 학습 시키는 코드
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)


# 데이터 불러오는 부분
batch_xs, batch_ys = mnist.train.next_batch(100)
# batch_xs -> 훈련데이터
# batch_ys -> 훈련데이터 라벨

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(accuracy, feed_dict = { x: batch_xs, y_onehot : batch_ys })) # accuracy로 바꿈

sess.run(train, feed_dict = { x: batch_xs, y_onehot : batch_ys })
sess.close()

## 문제95. 위의 코드에 for loop문을 추가해서 1에폭 돌게 하시오!

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 오차 확인
loss = -tf.reduce_sum(y_onehot * tf.log(z_hat), axis = 1)
result = tf.reduce_mean(loss)
# softmax를 통과한것을 tf.log부분에 넣어야 되기 때문에 z_hat이 들어간다.

# 학습 시키는 코드
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)
init = tf.global_variables_initializer() # 변수 초기화는 딱 1번만 하면됨.

# 세션 생성
sess = tf.Session()
sess.run(init)

# 데이터 불러오는 부분
for i in range(1,601): # 1epoch = 600번
    batch_xs, batch_ys = mnist.train.next_batch(100)
    # batch_xs -> 훈련데이터
    # batch_ys -> 훈련데이터 라벨
    sess.run(train, feed_dict = { x: batch_xs, y_onehot : batch_ys })
    print(sess.run(accuracy, feed_dict = { x: batch_xs, y_onehot : batch_ys })) # 정확도 출력을 위해 accuracy

## 문제96. 위의 코드를 20에폭 돌리시오~

In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

# 1층
x = tf.placeholder("float", [None,784])
W1 = tf.Variable(tf.random_uniform([784,50],-1,1))
b1 = tf.Variable(tf.ones([50]))

y = tf.matmul(x, W1) + b1
y_hat = tf.nn.relu(y) # tensorflow에서는 sigmoid함수를 안만들어도 이렇게 하면 된다.

# 2층 출력층
W2 = tf.Variable(tf.random_uniform([50,10],-1,1))
b2 = tf.Variable(tf.ones([10]))
z = tf.matmul(y_hat, W2) + b2
z_hat = tf.nn.softmax(z)
y_predict = tf.argmax(z_hat, axis=1)

# 정확도 확인
y_onehot = tf.placeholder("float", [None,10])
y_label = tf.argmax(y_onehot, axis =1)

correction_prediction = tf.equal(y_predict, y_label) # 같으면 True, 다르면 False
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float")) # True = 1, False = 0 으로 바꿈

# 오차 확인
loss = -tf.reduce_sum(y_onehot * tf.log(z_hat), axis = 1)
result = tf.reduce_mean(loss)
# softmax를 통과한것을 tf.log부분에 넣어야 되기 때문에 z_hat이 들어간다.

# 학습 시키는 코드
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)
init = tf.global_variables_initializer() # 변수 초기화는 딱 1번만 하면됨.

# 세션 생성
sess = tf.Session()
sess.run(init)

# 데이터 불러오는 부분
for i in range(1,601): # 1epoch = 600번
    batch_xs, batch_ys = mnist.train.next_batch(100)
    # batch_xs -> 훈련데이터
    # batch_ys -> 훈련데이터 라벨
    sess.run(train, feed_dict = { x: batch_xs, y_onehot : batch_ys })
    print(sess.run(accuracy, feed_dict = { x: batch_xs, y_onehot : batch_ys })) # 정확도 출력을 위해 accuracy